version: "5.0.1"
name: "printy-app"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5000 app:app
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL:?}
      - REDIS_URL=${REDIS_URL:?}

  frontend:
    build: ./frontend
    depends_on:
      - backend
    expose:
      - "80"
      - "443"

volumes:
  postgres_data:

