"""Add prints

Revision ID: 1766538580
Revises: 1766532155
Create Date: 2025-12-24 01:09:40.222200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1766538580'
down_revision: Union[str, Sequence[str], None] = '1766532155'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prints',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raster_data', sa.LargeBinary(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prints')
    # ### end Alembic commands ###
