"""Add print width and height

Revision ID: 1766542394
Revises: 1766538580
Create Date: 2025-12-24 02:13:14.153020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1766542394'
down_revision: Union[str, Sequence[str], None] = '1766538580'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prints', sa.Column('image_width', sa.Integer(), nullable=False))
    op.add_column('prints', sa.Column('image_height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prints', 'image_height')
    op.drop_column('prints', 'image_width')
    # ### end Alembic commands ###
